### ISSUE TITLE
Manipulate serilog log levels.

### ISSUE THREAD

**Issue by KanarekLife** [xxlo-devs/eru#29]

**Comment by Bazik33** [comment]
Is this issue about this type of manipulation serilog log levels? 
```
"MinimumLevel": {
    "Default": "Information",
    "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
    }
}
```
(source: [https://github.com/serilog/serilog-settings-configuration](https://github.com/serilog/serilog-settings-configuration))
